SELECT * FROM DG_TRAINER WHERE TRAINERID IN 
    (SELECT TRAINERID FROM 
       (SELECT T.TRAINERID, COUNT(*) C FROM DG_TRADE T GROUP BY T.TRAINERID HAVING COUNT(*) > 0 ORDER BY C DESC) 
    WHERE ROWNUM <= 3) C
    
    SELECT * FROM 
    (
    	SELECT 
    	T.TRAINERID 
    	RANK() OVER (PARTITION BY T.TRAINERID ORDER BY T.TRAINERID) AS 랭킹
    	FROM DG_TRADE T
    	INNER JOIN DG_TRAINER D ON T.TRAINERID = D.TRAINERID
    )
    WHERE 랭킹 <= 3
    
