
SELECT * FROM TABLE_USER;
SELECT * FROM TABLE_BOARD_POINT;
SELECT * FROM TABLE_BOARD_EVENT;
SELECT * FROM TABLE_FILES_EVENT;
SELECT * FROM TABLE_FILES_REVIEW;
SELECT * FROM TABLE_REPLY_EVENT;


-- 게시판 유저 닉네임