
SELECT * FROM TABLE_USER;
SELECT * FROM TABLE_BOARD_POINT;
SELECT * FROM TABLE_BOARD_EVENT;
SELECT * FROM TABLE_FILES_EVENT;
SELECT * FROM TABLE_FILES_REVIEW;
SELECT * FROM TABLE_REPLY_EVENT;


-- 게시판 유저 닉네임
INSERT INTO TABLE_USER
(USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_EMAIL_HASH, USER_ZIPCODE, USER_ADDRESS, USER_ADDRESS_DETAIL, USER_ADDRESS_ETC, USER_POINT)
VALUES('test1', '1234', 'test', 'test', 'test', '16577', '경기도 수원', 'aa', 'aa', 0);


INSERT INTO TABLE_BOARD_REVIEW
(BOARD_NUM, BOARD_TITLE, BOARD_CONTENT, BOARD_ID, BOARD_VIEW, BOARD_DATE, BOARD_CATEGORY)
VALUES(BOARD_SEQ_REVIEW.NEXTVAL, '부산sdfsdfsdfsdf', '호캉스', 'admin', 0, SYSDATE, 'REVIEW');


INSERT INTO TABLE_BOARD_FREETALK
(BOARD_NUM, BOARD_TITLE, BOARD_CONTENT, BOARD_ID, BOARD_VIEW, BOARD_DATE, BOARD_CATEGORY)
VALUES(BOARD_SEQ_FREETALK.NEXTVAL, '부산dfsdfsdfsdfsdfsdfsdf이이s가나다라마바사아자차카타파하', '아이유2', 'test2', 0, SYSDATE, 'FREE');


SELECT * FROM TABLE_BOARD_REVIEW;
SELECT * FROM TABLE_BOARD_FREETALK tbf;

